/*

 KENBAKBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define KenbakBackgroundMapWidth 20
#define KenbakBackgroundMapHeight 18
#define KenbakBackgroundMapBank 0

extern unsigned char KenbakBackgroundMap[];

/* End of KENBAKBACKGROUNDMAP.H */
