/*

 KENBAKMENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define KenbakMenuMapWidth 20
#define KenbakMenuMapHeight 18
#define KenbakMenuMapBank 0

extern unsigned char KenbakMenuMap[];

/* End of KENBAKMENUMAP.H */
